language: c

sudo: true

script:
  - Rscript -e "source('test_lesson.R');setwd('..');test_course('DataScienceAndR')"

after_failure:
  - ./travis-tool.sh dump_logs

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - Rscript -e "install.packages('swirl', repos = 'http://cran.r-project.org')"
  - Rscript -e "setwd('..');install_course_directory('DataScienceAndR')"

notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - BOOTSTRAP_LATEX=0