language: c

sudo: true

script: 
  - Rscript -e "source('.test_course.R')"

after_failure:
  - ./travis-tool.sh dump_logs

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - sudo apt-get install -y libcurl4-openssl-dev
  - Rscript -e "source('http://wush978.github.io/R/init-swirl.R')"

notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - BOOTSTRAP_LATEX=0
