# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - Rscript -e "install.packages('swirl', repos = 'http://cran.r-project.org')"

test_script:
  - Rscript -e 'eval(expr = parse(text = RCurl::getURL("https://gist.githubusercontent.com/ChihChengLiang/516aae373c6a27e95d02/raw/95705dde3f298d0fc462cf4e40689eae50bf6da9/test_lesson.R")));test_course("DataScienceAndR/")'

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits